import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Typography, Paper, Card, CardContent, Button } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { Database as BackupIcon, Palette as SwatchIcon } from 'lucide-react';
import { Assignment as AssignmentIcon } from '@mui/icons-material';
const Admin = () => {
    const navigate = useNavigate();
    return (_jsxs(Box, { children: [_jsx(Typography, { variant: "h4", gutterBottom: true, children: "Administration" }), _jsx(Paper, { sx: { p: 3 }, children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: [_jsx(Card, { className: "hover:shadow-lg transition-shadow duration-300 cursor-pointer", onClick: () => navigate('/qa-checklist'), children: _jsxs(CardContent, { className: "p-6", children: [_jsxs("div", { className: "flex items-center mb-4", children: [_jsx(AssignmentIcon, { className: "text-green-600 mr-3", sx: { fontSize: 32 } }), _jsx(Typography, { variant: "h6", className: "font-semibold", children: "QA Launch Checklist" })] }), _jsx(Typography, { variant: "body2", className: "text-gray-600 dark:text-gray-400 mb-4", children: "Pre-launch validation checklist for all system components" }), _jsx(Button, { variant: "outlined", fullWidth: true, children: "Open Checklist" })] }) }), _jsx(Card, { className: "hover:shadow-lg transition-shadow duration-300 cursor-pointer", onClick: () => navigate('/backup'), children: _jsxs(CardContent, { className: "p-6", children: [_jsxs("div", { className: "flex items-center mb-4", children: [_jsx(BackupIcon, { className: "text-blue-600 mr-3", sx: { fontSize: 32 } }), _jsx(Typography, { variant: "h6", className: "font-semibold", children: "Backup & Recovery" })] }), _jsx(Typography, { variant: "body2", className: "text-gray-600 dark:text-gray-400 mb-4", children: "Secure data backup and restore for all user-generated content" }), _jsx(Button, { variant: "outlined", fullWidth: true, children: "Manage Backups" })] }) }), _jsx(Card, { className: "hover:shadow-lg transition-shadow duration-300 cursor-pointer", onClick: () => navigate('/whitelabel'), children: _jsxs(CardContent, { className: "p-6", children: [_jsxs("div", { className: "flex items-center mb-4", children: [_jsx(SwatchIcon, { className: "text-purple-600 mr-3", sx: { fontSize: 32 } }), _jsx(Typography, { variant: "h6", className: "font-semibold", children: "Whitelabel Configuration" })] }), _jsx(Typography, { variant: "body2", className: "text-gray-600 dark:text-gray-400 mb-4", children: "Customize branding, colors, and appearance for your tenant" }), _jsx(Button, { variant: "outlined", fullWidth: true, children: "Configure Branding" })] }) }), _jsx(Typography, { variant: "body1", children: "System administration and user management features will be implemented here." })] }) })] }));
};
export default Admin;
