import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Container, Paper, Typography, Box } from '@mui/material';
import { useTranslation } from 'react-i18next';
import { TransferPricingForm } from '../components/transferPricing/TransferPricingForm';
export const TransferPricing = () => {
    const { t } = useTranslation();
    return (_jsxs(Container, { maxWidth: "lg", sx: { py: 4 }, children: [_jsxs(Paper, { sx: { p: 3, mb: 3 }, children: [_jsx(Typography, { variant: "h4", gutterBottom: true, children: t('transferPricing.title') }), _jsx(Typography, { variant: "body1", color: "text.secondary", paragraph: true, children: t('transferPricing.description') })] }), _jsx(TransferPricingForm, {}), _jsx(Paper, { elevation: 0, className: "p-6 bg-white dark:bg-gray-800 rounded-xl shadow-sm mb-6", children: _jsxs(Box, { className: "flex items-start gap-6", children: [_jsx(Box, { className: "flex-1", children: _jsx(Typography, { variant: "h6", className: "text-gray-900 dark:text-white font-semibold mb-4", children: t('transferPricing.documentation.title', 'Master File / Local File / CbC Upload') }) }), _jsx("div", { className: "hidden md:block", children: _jsx("img", { src: "/images/peergos_slide_13.png", alt: "Transfer Pricing Documentation", className: "w-32 h-24 object-cover rounded-lg opacity-60" }) })] }) }), _jsxs("div", { className: "bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 mb-8", children: [_jsx("div", { className: "px-6 py-4 border-b border-gray-200 dark:border-gray-700", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 dark:text-white flex items-center", children: "\uD83D\uDD04 Automated Related Party Tracking" }), _jsx("p", { className: "text-sm text-gray-600 dark:text-gray-400 mt-1", children: "Automatic detection and compliance monitoring for transfer pricing" })] }), _jsx("span", { className: "px-3 py-1 text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-200 rounded-full", children: "AI-Powered" })] }) }), _jsx("div", { className: "p-6", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 border border-blue-200 dark:border-blue-700", children: [_jsx("h4", { className: "font-medium text-blue-800 dark:text-blue-200 mb-2", children: "Transaction Monitoring" }), _jsx("p", { className: "text-sm text-blue-600 dark:text-blue-300", children: "Automatically identifies related party transactions and flags for transfer pricing review" })] }), _jsxs("div", { className: "bg-purple-50 dark:bg-purple-900/20 rounded-lg p-4 border border-purple-200 dark:border-purple-700", children: [_jsx("h4", { className: "font-medium text-purple-800 dark:text-purple-200 mb-2", children: "Compliance Alerts" }), _jsx("p", { className: "text-sm text-purple-600 dark:text-purple-300", children: "Real-time notifications for transfer pricing documentation requirements" })] })] }) })] }), _jsx("div", { className: "bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 mb-8" })] }));
};
export default TransferPricing;
