import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const RelatedPartyTable = ({ transactions }) => {
    return (_jsx("div", { className: "overflow-x-auto rounded-lg border border-gray-200 dark:border-gray-700", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200 dark:divide-gray-700", children: [_jsx("thead", { className: "bg-gray-50 dark:bg-gray-800", children: _jsxs("tr", { children: [_jsx("th", { scope: "col", className: "px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider", children: "Party Name" }), _jsx("th", { scope: "col", className: "px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider", children: "Relationship" }), _jsx("th", { scope: "col", className: "px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider", children: "Country" }), _jsx("th", { scope: "col", className: "px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider", children: "Transaction Type" }), _jsx("th", { scope: "col", className: "px-4 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider", children: "Value (AED)" })] }) }), _jsx("tbody", { className: "bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700", children: transactions.map((transaction) => (_jsxs("tr", { className: "hover:bg-gray-50 dark:hover:bg-gray-700", children: [_jsx("td", { className: "px-4 py-3 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-white", children: transaction.partyName }), _jsx("td", { className: "px-4 py-3 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400", children: transaction.relationship }), _jsx("td", { className: "px-4 py-3 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400", children: transaction.country }), _jsx("td", { className: "px-4 py-3 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400", children: transaction.transactionType }), _jsx("td", { className: "px-4 py-3 whitespace-nowrap text-sm text-right text-gray-500 dark:text-gray-400", children: new Intl.NumberFormat('en-AE', {
                                    style: 'currency',
                                    currency: 'AED',
                                    minimumFractionDigits: 0,
                                    maximumFractionDigits: 0,
                                }).format(transaction.value) })] }, transaction.id))) })] }) }));
};
export default RelatedPartyTable;
