import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router-dom';
import ProtectedRoute from './components/ProtectedRoute';
import Layout from './components/Layout';
import Dashboard from './pages/Dashboard';
import Assistant from './pages/Assistant';
import Admin from './pages/Admin';
import Financials from './pages/Financials';
import Setup from './pages/Setup';
import Filing from './pages/Filing';
import { TaxProvider } from './context/TaxContext';
import { ThemeProvider } from './context/ThemeContext';
import { RelatedPartyProvider } from './context/RelatedPartyContext';
import { SettingsProvider } from './context/SettingsContext';
import { I18nextProvider } from 'react-i18next';
import i18n from './i18n';
import { TransferPricingPage } from './pages/TransferPricingPage';
const App = () => {
    return (_jsx(SettingsProvider, { children: _jsx(ThemeProvider, { children: _jsx(TaxProvider, { children: _jsx(RelatedPartyProvider, { children: _jsx(I18nextProvider, { i18n: i18n, children: _jsx(Layout, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(ProtectedRoute, { path: "/", resource: "dashboard", children: _jsx(Dashboard, {}) }) }), _jsx(Route, { path: "/dashboard", element: _jsx(ProtectedRoute, { path: "/dashboard", resource: "dashboard", children: _jsx(Dashboard, {}) }) }), _jsx(Route, { path: "/setup", element: _jsx(ProtectedRoute, { path: "/setup", resource: "setup", children: _jsx(Setup, {}) }) }), _jsx(Route, { path: "/filing", element: _jsx(ProtectedRoute, { path: "/filing", resource: "filing", children: _jsx(Filing, {}) }) }), _jsx(Route, { path: "/assistant", element: _jsx(ProtectedRoute, { path: "/assistant", resource: "assistant", children: _jsx(Assistant, {}) }) }), _jsx(Route, { path: "/admin", element: _jsx(ProtectedRoute, { path: "/admin", resource: "dashboard", requiredPermission: "edit", children: _jsx(Admin, {}) }) }), _jsx(Route, { path: "/financials", element: _jsx(ProtectedRoute, { path: "/financials", resource: "dashboard", children: _jsx(Financials, {}) }) }), _jsx(Route, { path: "/transfer-pricing", element: _jsx(ProtectedRoute, { path: "/transfer-pricing", resource: "transfer-pricing", children: _jsx(TransferPricingPage, {}) }) }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/setup", replace: true }) })] }) }) }) }) }) }) }));
};
export default App;
