import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import './index.css';
import App from './App.tsx';
import { AuditProvider } from './context/AuditContext';
import { UserRoleProvider } from './context/UserRoleContext';
import { AppContextProvider } from './context/AppContext';
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsx(AppContextProvider, { children: _jsx(AuditProvider, { children: _jsx(UserRoleProvider, { children: _jsx(BrowserRouter, { children: _jsx(App, {}) }) }) }) }) }));
